// Package storage confines snapshot writes to the configured current-user
// document root. It only accepts relative paths generated by the service.
package storage

import (
	"archive/zip"
	"bufio"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	_ "modernc.org/sqlite"
)

const ProductDirectory = "MimiAppBakcup"

type Store struct{ base string }

type Partial struct {
	Directory string
	Archive   string
}

type Location struct {
	Directory string
	Archive   string
}

type FileIndexEntry struct {
	Path     string    `json:"path"`
	Type     string    `json:"type"`
	Size     int64     `json:"size"`
	Modified time.Time `json:"modified"`
}

type Usage struct {
	ArchiveBytes   int64
	AvailableBytes int64
	PartialCount   int
	TrashCount     int
}

// LocationStatus reports whether a persisted snapshot directory can still be
// reached from the current user's document root. It intentionally checks only
// the directory itself; archive integrity remains an explicit maintenance
// operation and is not triggered by opening the backup-library detail view.
func (s *Store) LocationStatus(location Location) string {
	directory, err := s.resolve(location.Directory)
	if err != nil {
		return "INACCESSIBLE"
	}
	info, err := os.Lstat(directory)
	if errors.Is(err, os.ErrNotExist) {
		return "MISSING"
	}
	if err != nil || info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return "INACCESSIBLE"
	}
	return "AVAILABLE"
}

func New(documentRoot string) (*Store, error) {
	if strings.TrimSpace(documentRoot) == "" {
		return nil, errors.New("document root is required")
	}
	root, err := filepath.Abs(filepath.Clean(documentRoot))
	if err != nil {
		return nil, fmt.Errorf("resolve document root: %w", err)
	}
	if err := os.MkdirAll(root, 0o700); err != nil {
		return nil, fmt.Errorf("create document root: %w", err)
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return nil, fmt.Errorf("resolve document root: %w", err)
	}
	store := &Store{base: filepath.Join(root, ProductDirectory)}
	if err := os.MkdirAll(store.base, 0o700); err != nil {
		return nil, err
	}
	info, err := os.Lstat(store.base)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return nil, errors.New("backup storage root is not a safe directory")
	}
	if err := store.ensureWithin(store.base); err != nil {
		return nil, err
	}
	return store, nil
}

func (s *Store) CreatePartial(jobID string) (Partial, error) {
	if err := safeSegment(jobID); err != nil {
		return Partial{}, err
	}
	directory := path.Join("_partial", jobID)
	if err := s.makeDirectories(directory); err != nil {
		return Partial{}, err
	}
	archive, err := s.resolve(path.Join(directory, "snapshot.zip"))
	if err != nil {
		return Partial{}, err
	}
	return Partial{Directory: directory, Archive: archive}, nil
}

func (s *Store) CreateArchive(partial Partial) (*os.File, error) {
	if err := s.ensureWithin(partial.Archive); err != nil {
		return nil, err
	}
	return os.OpenFile(partial.Archive, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
}

func (s *Store) DiscardArchive(partial Partial) error {
	if err := s.ensureWithin(partial.Archive); err != nil {
		return err
	}
	err := os.Remove(partial.Archive)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return err
}

// CommitArchive moves a finished archive to its final directory. The caller
// must still write the external manifest last before treating it as a snapshot.
func (s *Store) CommitArchive(partial Partial, timestamp, deployID, suffix string) (Location, error) {
	if err := safeSegment(timestamp); err != nil {
		return Location{}, err
	}
	if err := safeSegment(deployID); err != nil {
		return Location{}, err
	}
	if err := safeSegment(suffix); err != nil {
		return Location{}, err
	}
	if err := s.ensureWithin(partial.Archive); err != nil {
		return Location{}, err
	}
	parent := timestamp
	directory := path.Join(parent, deployID)
	if _, err := s.resolve(directory); err != nil {
		return Location{}, err
	}
	if _, err := os.Lstat(mustResolve(s, directory)); err == nil {
		parent += "-" + suffix
		directory = path.Join(parent, deployID)
	}
	if err := s.makeDirectories(directory); err != nil {
		return Location{}, err
	}
	archive, err := s.resolve(path.Join(directory, "snapshot.zip"))
	if err != nil {
		return Location{}, err
	}
	if err := os.Rename(partial.Archive, archive); err != nil {
		return Location{}, fmt.Errorf("commit archive: %w", err)
	}
	return Location{Directory: directory, Archive: archive}, nil
}

func (s *Store) WriteManifest(location Location, data []byte) error {
	directory, err := s.resolve(location.Directory)
	if err != nil {
		return err
	}
	if err := s.ensureWithin(location.Archive); err != nil {
		return err
	}
	temporary := filepath.Join(directory, ".manifest.json.tmp")
	if err := s.ensureWithin(temporary); err != nil {
		return err
	}
	file, err := os.OpenFile(temporary, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return fmt.Errorf("create manifest: %w", err)
	}
	_, writeErr := file.Write(data)
	if writeErr == nil {
		writeErr = file.Sync()
	}
	closeErr := file.Close()
	if writeErr != nil {
		_ = os.Remove(temporary)
		return fmt.Errorf("write manifest: %w", writeErr)
	}
	if closeErr != nil {
		_ = os.Remove(temporary)
		return fmt.Errorf("close manifest: %w", closeErr)
	}
	if err := os.Rename(temporary, filepath.Join(directory, "manifest.json")); err != nil {
		return fmt.Errorf("commit manifest: %w", err)
	}
	return syncDirectory(directory)
}

func (s *Store) Digest(pathname string) (int64, string, error) {
	if err := s.ensureWithin(pathname); err != nil {
		return 0, "", err
	}
	file, err := os.Open(pathname)
	if err != nil {
		return 0, "", err
	}
	defer file.Close()
	hash := sha256.New()
	size, err := io.Copy(hash, file)
	if err != nil {
		return 0, "", err
	}
	return size, hex.EncodeToString(hash.Sum(nil)), nil
}

func (s *Store) SyncArchive(pathname string) error {
	if err := s.ensureWithin(pathname); err != nil {
		return err
	}
	file, err := os.Open(pathname)
	if err != nil {
		return err
	}
	defer file.Close()
	return file.Sync()
}

func (s *Store) QuickVerify(location Location, expectedSize int64, expectedSHA256 string) error {
	archive, err := s.resolve(path.Join(location.Directory, "snapshot.zip"))
	if err != nil {
		return err
	}
	manifest, err := s.resolve(path.Join(location.Directory, "manifest.json"))
	if err != nil {
		return err
	}
	if _, err := os.Stat(manifest); err != nil {
		return fmt.Errorf("read manifest: %w", err)
	}
	actualSize, actualSHA256, err := s.Digest(archive)
	if err != nil {
		return err
	}
	if actualSize != expectedSize || actualSHA256 != expectedSHA256 {
		return errors.New("archive digest mismatch")
	}
	reader, err := zip.OpenReader(archive)
	if err != nil {
		return fmt.Errorf("open archive: %w", err)
	}
	defer reader.Close()
	foundManifest := false
	for _, entry := range reader.File {
		if !safeZipPath(entry.Name) {
			return errors.New("unsafe archive entry")
		}
		if entry.Name == "_snapshot/manifest.json" {
			foundManifest = true
		}
	}
	if !foundManifest {
		return errors.New("internal manifest is missing")
	}
	return nil
}

func (s *Store) FileIndex(location Location, limit int) ([]FileIndexEntry, error) {
	if limit <= 0 || limit > 10000 {
		limit = 10000
	}
	archive, err := s.resolve(path.Join(location.Directory, "snapshot.zip"))
	if err != nil {
		return nil, err
	}
	reader, err := zip.OpenReader(archive)
	if err != nil {
		return nil, err
	}
	defer reader.Close()
	for _, entry := range reader.File {
		if !safeZipPath(entry.Name) {
			return nil, errors.New("unsafe archive entry")
		}
		if entry.Name != "_snapshot/file-index.jsonl" {
			continue
		}
		file, err := entry.Open()
		if err != nil {
			return nil, err
		}
		defer file.Close()
		scanner := bufio.NewScanner(file)
		scanner.Buffer(make([]byte, 1024), 1024*1024)
		result := []FileIndexEntry{}
		for scanner.Scan() {
			if len(result) >= limit {
				break
			}
			var item FileIndexEntry
			if err := json.Unmarshal(scanner.Bytes(), &item); err != nil {
				return nil, fmt.Errorf("read file index: %w", err)
			}
			if !safeZipPath("appvar/"+item.Path) || item.Path == "" {
				return nil, errors.New("unsafe file index path")
			}
			result = append(result, item)
		}
		if err := scanner.Err(); err != nil {
			return nil, err
		}
		return result, nil
	}
	return nil, errors.New("file index is missing")
}

func (s *Store) FullVerify(location Location, expectedSize int64, expectedSHA256 string) error {
	if err := s.QuickVerify(location, expectedSize, expectedSHA256); err != nil {
		return err
	}
	archive, err := s.resolve(path.Join(location.Directory, "snapshot.zip"))
	if err != nil {
		return err
	}
	reader, err := zip.OpenReader(archive)
	if err != nil {
		return err
	}
	defer reader.Close()
	verificationRoot, err := s.resolve("_partial")
	if err != nil {
		return err
	}
	if err := s.makeDirectories("_partial"); err != nil {
		return err
	}
	verificationDirectory, err := os.MkdirTemp(verificationRoot, "verify-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(verificationDirectory)
	for index, entry := range reader.File {
		if !safeZipPath(entry.Name) || entry.Mode()&os.ModeSymlink != 0 {
			return errors.New("unsafe archive entry")
		}
		if entry.FileInfo().IsDir() {
			continue
		}
		file, err := entry.Open()
		if err != nil {
			return err
		}
		var header [16]byte
		read, readErr := io.ReadFull(file, header[:])
		if readErr != nil && !errors.Is(readErr, io.ErrUnexpectedEOF) && !errors.Is(readErr, io.EOF) {
			_ = file.Close()
			return readErr
		}
		isSQLite := read == len(header) && string(header[:]) == "SQLite format 3\x00"
		var copyErr error
		if isSQLite {
			temporary := filepath.Join(verificationDirectory, fmt.Sprintf("%d.sqlite", index))
			output, err := os.OpenFile(temporary, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
			if err != nil {
				_ = file.Close()
				return err
			}
			_, copyErr = output.Write(header[:])
			if copyErr == nil {
				_, copyErr = io.Copy(output, file)
			}
			outputErr := output.Close()
			if copyErr == nil {
				copyErr = outputErr
			}
			if copyErr == nil {
				copyErr = quickCheckSQLite(temporary)
			}
		} else {
			_, copyErr = io.Copy(io.Discard, file)
		}
		closeErr := file.Close()
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
	}
	return nil
}

func quickCheckSQLite(filename string) error {
	database, err := sql.Open("sqlite", filename)
	if err != nil {
		return err
	}
	defer database.Close()
	var result string
	if err := database.QueryRow("PRAGMA quick_check").Scan(&result); err != nil {
		return err
	}
	if result != "ok" {
		return fmt.Errorf("sqlite quick_check: %s", result)
	}
	return nil
}

// ExportData extracts appvar entries into a new current-user document-root
// directory. Metadata remains inside the original archive and no target appvar
// path is ever used as a destination.
func (s *Store) ExportData(location Location, exportID string) (string, error) {
	if err := safeSegment(exportID); err != nil {
		return "", err
	}
	archive, err := s.resolve(path.Join(location.Directory, "snapshot.zip"))
	if err != nil {
		return "", err
	}
	destinationRelative := path.Join("_restore_exports", exportID)
	if err := s.makeDirectories("_restore_exports"); err != nil {
		return "", err
	}
	destination, err := s.resolve(destinationRelative)
	if err != nil {
		return "", err
	}
	if _, err := os.Lstat(destination); !errors.Is(err, os.ErrNotExist) {
		if err == nil {
			return "", errors.New("export destination already exists")
		}
		return "", err
	}
	if err := os.Mkdir(destination, 0o700); err != nil {
		return "", err
	}
	cleanup := true
	defer func() {
		if cleanup {
			_ = s.RemoveDirectory(destinationRelative)
		}
	}()
	reader, err := zip.OpenReader(archive)
	if err != nil {
		return "", err
	}
	defer reader.Close()
	for _, entry := range reader.File {
		if !safeZipPath(entry.Name) || entry.Mode()&os.ModeSymlink != 0 {
			return "", errors.New("unsafe archive entry")
		}
		if !strings.HasPrefix(entry.Name, "appvar/") {
			continue
		}
		relative := strings.TrimPrefix(entry.Name, "appvar/")
		if relative == "" {
			continue
		}
		target := filepath.Join(destination, filepath.FromSlash(relative))
		if err := ensureChild(destination, target); err != nil {
			return "", err
		}
		if entry.FileInfo().IsDir() {
			if err := os.MkdirAll(target, 0o700); err != nil {
				return "", err
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
			return "", err
		}
		output, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
		if err != nil {
			return "", err
		}
		input, err := entry.Open()
		if err == nil {
			_, err = io.Copy(output, input)
			closeErr := input.Close()
			if err == nil {
				err = closeErr
			}
		}
		outputErr := output.Close()
		if err != nil {
			return "", err
		}
		if outputErr != nil {
			return "", outputErr
		}
	}
	cleanup = false
	return destinationRelative, nil
}

func (s *Store) MoveToTrash(location Location, trashID string) (Location, error) {
	if err := safeSegment(trashID); err != nil {
		return Location{}, err
	}
	source, err := s.resolve(location.Directory)
	if err != nil {
		return Location{}, err
	}
	if err := s.makeDirectories("_trash"); err != nil {
		return Location{}, err
	}
	destinationRelative := path.Join("_trash", trashID)
	destination, err := s.resolve(destinationRelative)
	if err != nil {
		return Location{}, err
	}
	if _, err := os.Lstat(destination); !errors.Is(err, os.ErrNotExist) {
		if err == nil {
			return Location{}, errors.New("trash destination already exists")
		}
		return Location{}, err
	}
	if err := os.Rename(source, destination); err != nil {
		return Location{}, err
	}
	return Location{Directory: destinationRelative, Archive: filepath.Join(destination, "snapshot.zip")}, nil
}

func (s *Store) RemoveExpiredChildren(parent string, before time.Time) (int, error) {
	if parent != "_partial" && parent != "_trash" {
		return 0, errors.New("unsafe maintenance parent")
	}
	directory, err := s.resolve(parent)
	if err != nil {
		return 0, err
	}
	entries, err := os.ReadDir(directory)
	if errors.Is(err, os.ErrNotExist) {
		return 0, nil
	}
	if err != nil {
		return 0, err
	}
	removed := 0
	for _, entry := range entries {
		if entry.Type()&os.ModeSymlink != 0 || !entry.IsDir() {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			return removed, err
		}
		if info.ModTime().After(before) {
			continue
		}
		if err := s.RemoveDirectory(path.Join(parent, entry.Name())); err != nil {
			return removed, err
		}
		removed++
	}
	return removed, nil
}

func (s *Store) Usage() (Usage, error) {
	usage := Usage{}
	var stat syscall.Statfs_t
	if err := syscall.Statfs(s.base, &stat); err != nil {
		return usage, err
	}
	usage.AvailableBytes = int64(stat.Bavail) * int64(stat.Bsize)
	entries, err := os.ReadDir(s.base)
	if err != nil {
		return usage, err
	}
	for _, entry := range entries {
		if entry.Type()&os.ModeSymlink != 0 {
			return usage, errors.New("storage root contains a symbolic link")
		}
		switch entry.Name() {
		case "_partial":
			children, err := os.ReadDir(filepath.Join(s.base, entry.Name()))
			if err != nil {
				return usage, err
			}
			usage.PartialCount = len(children)
		case "_trash":
			children, err := os.ReadDir(filepath.Join(s.base, entry.Name()))
			if err != nil {
				return usage, err
			}
			usage.TrashCount = len(children)
		default:
			if !entry.IsDir() {
				continue
			}
			pathway := filepath.Join(s.base, entry.Name())
			err := filepath.WalkDir(pathway, func(pathname string, item os.DirEntry, walkErr error) error {
				if walkErr != nil {
					return walkErr
				}
				if item.Type()&os.ModeSymlink != 0 {
					return errors.New("storage path contains a symbolic link")
				}
				if item.IsDir() || item.Name() != "snapshot.zip" {
					return nil
				}
				info, err := item.Info()
				if err != nil {
					return err
				}
				usage.ArchiveBytes += info.Size()
				return nil
			})
			if err != nil {
				return usage, err
			}
		}
	}
	return usage, nil
}

func (s *Store) RemoveDirectory(relative string) error {
	target, err := s.resolve(relative)
	if err != nil {
		return err
	}
	if err := s.ensureWithin(target); err != nil {
		return err
	}
	info, err := os.Lstat(target)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return errors.New("storage target is a symbolic link")
	}
	return os.RemoveAll(target)
}

func (s *Store) resolve(relative string) (string, error) {
	if !safeRelative(relative) {
		return "", errors.New("unsafe storage relative path")
	}
	result := filepath.Join(s.base, filepath.FromSlash(relative))
	if err := s.ensureWithin(result); err != nil {
		return "", err
	}
	return result, nil
}

func mustResolve(s *Store, relative string) string {
	result, _ := s.resolve(relative)
	return result
}

func (s *Store) ensureWithin(target string) error {
	relative, err := filepath.Rel(s.base, target)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return errors.New("storage path escapes document root")
	}
	current := s.base
	for _, segment := range strings.Split(relative, string(filepath.Separator)) {
		if segment == "." || segment == "" {
			continue
		}
		current = filepath.Join(current, segment)
		info, err := os.Lstat(current)
		if errors.Is(err, os.ErrNotExist) {
			break
		}
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return errors.New("storage path contains a symbolic link")
		}
	}
	return nil
}

func (s *Store) makeDirectories(relative string) error {
	target, err := s.resolve(relative)
	if err != nil {
		return err
	}
	if err := s.ensureWithin(target); err != nil {
		return err
	}
	if err := os.MkdirAll(target, 0o700); err != nil {
		return fmt.Errorf("create storage directory: %w", err)
	}
	return s.ensureWithin(target)
}

func safeRelative(value string) bool {
	if value == "" || path.IsAbs(value) || filepath.IsAbs(value) {
		return false
	}
	clean := path.Clean(value)
	return clean == value && clean != "." && clean != ".." && !strings.HasPrefix(clean, "../")
}

func safeSegment(value string) error {
	if value == "" || value == "." || value == ".." || strings.ContainsAny(value, "/\\") {
		return errors.New("unsafe storage path segment")
	}
	return nil
}

func safeZipPath(value string) bool {
	if value == "" || strings.HasPrefix(value, "/") {
		return false
	}
	trimmed := strings.TrimSuffix(value, "/")
	return trimmed != "" && path.Clean(trimmed) == trimmed && trimmed != ".." && !strings.HasPrefix(trimmed, "../")
}

func ensureChild(root, target string) error {
	relative, err := filepath.Rel(root, target)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return errors.New("archive path escapes export root")
	}
	return nil
}

func syncDirectory(directory string) error {
	file, err := os.Open(directory)
	if err != nil {
		return err
	}
	defer file.Close()
	return file.Sync()
}
