package: cloud.lazycat.app.mimi-app-backup
version: 0.1.5
name: 咪咪应用备份
description: 自动备份懒猫应用数据
author: dnwwdwd
homepage: https://github.com/dnwwdwd/lazycat-app-snapshot
license: MIT
min_os_version: "1.5.0"

locales:
  zh:
    name: 咪咪应用备份
    description: 自动备份懒猫应用数据
  zh_CN:
    name: 咪咪应用备份
    description: 自动备份懒猫应用数据
  en:
    name: Mimi App Backup
    description: Automatically back up Lazycat application data
  ja:
    name: Mimi App Backup
    description: Lazycat アプリケーションデータを自動的にバックアップします

permissions:
  required:
    - appvar.other.read
    - document.write
  optional:
    - user.notify
