// Data copied from designs/index.html
export const applications = [
  {
    id: "notus",
    name: "Notus 笔记",
    appid: "cloud.lazycat.notus",
    version: "2.4.1",
    mode: "single",
    deploy: "dep-notus-8839a",
    status: "BACKUPABLE_SHARED_WARNING",
    protection: "PROTECTED",
    size: "420 MB",
    bytes: 420,
    files: "1,420",
    sqlite: 2,
    last: "今天 02:00",
    next: "明天 02:00",
    color: "#3eab91",
    initials: "N",
    updated: "刚刚同步",
  },
  {
    id: "paperless",
    name: "Paperless 文档",
    appid: "cloud.lazycat.paperless",
    version: "2.11.0",
    mode: "multi",
    deploy: "dep-paper-1002",
    status: "BACKUPABLE",
    protection: "PROTECTED",
    size: "3.4 GB",
    bytes: 3400,
    files: "8,900",
    sqlite: 1,
    last: "今天 02:01",
    next: "明天 02:00",
    color: "#7e88de",
    initials: "P",
    updated: "刚刚同步",
  },
  {
    id: "immich",
    name: "Immich 相册",
    appid: "cloud.lazycat.immich",
    version: "1.112.0",
    mode: "multi",
    deploy: "dep-immich-1001",
    status: "BACKUPABLE",
    protection: "UNPROTECTED",
    size: "18.7 GB",
    bytes: 18700,
    files: "24,680",
    sqlite: 1,
    last: "—",
    next: "未设置",
    color: "#df6d7e",
    initials: "I",
    updated: "3 分钟前",
  },
  {
    id: "mastodon",
    name: "Mastodon 联邦微服",
    appid: "cloud.lazycat.mastodon",
    version: "4.2.8",
    mode: "single",
    deploy: "dep-masto-shared",
    status: "UNSUPPORTED_DATABASE",
    protection: "UNPROTECTED",
    size: "8.2 GB",
    bytes: 8200,
    files: "12,000",
    sqlite: 0,
    last: "—",
    next: "—",
    color: "#5d739d",
    initials: "M",
    unsupported: "PostgreSQL · 服务型数据库",
    updated: "6 分钟前",
  },
  {
    id: "vault",
    name: "Vaultwarden 密码库",
    appid: "cloud.lazycat.vaultwarden",
    version: "1.31.0",
    mode: "multi",
    deploy: "dep-vault-1001",
    status: "NO_DATA",
    protection: "UNPROTECTED",
    size: "0 B",
    bytes: 0,
    files: "0",
    sqlite: 0,
    last: "—",
    next: "—",
    color: "#e9941d",
    initials: "V",
    updated: "12 分钟前",
  },
];

export const plans = [
  {
    id: "plan-notus",
    name: "Notus 夜间守护",
    targets: "Notus 笔记",
    count: "1 个实例",
    schedule: "每天 · 02:00",
    next: "明天 02:00",
    retention: "7 日 / 4 周",
    on: true,
    result: "成功 · 420 MB",
  },
  {
    id: "plan-docs",
    name: "文档双保险",
    targets: "Paperless + Immich",
    count: "2 个实例",
    schedule: "每周一 · 03:30",
    next: "下周一 03:30",
    retention: "30 日 / 12 周",
    on: true,
    result: "成功 · 22.1 GB",
  },
  {
    id: "plan-manual",
    name: "新应用观察组",
    targets: "未来新增可备份应用",
    count: "动态目标",
    schedule: "仅手动",
    next: "—",
    retention: "最近 3 份",
    on: false,
    result: "尚未执行",
  },
];

export const snapshots = [
  {
    id: "snap-0827-notus",
    app: "Notus 笔记",
    deploy: "dep-notus-8839a",
    time: "2026-08-27 02:00:18",
    raw: "420 MB",
    zip: "188 MB",
    files: "1,420",
    sqlite: "2",
    integrity: "VERIFIED",
    keep: "保留至 09-03",
    mode: "single",
    sha: "4b22…e91a",
  },
  {
    id: "snap-0827-paperless",
    app: "Paperless 文档",
    deploy: "dep-paper-1002",
    time: "2026-08-27 02:01:46",
    raw: "3.4 GB",
    zip: "1.2 GB",
    files: "8,900",
    sqlite: "1",
    integrity: "VERIFIED",
    keep: "保留至 09-26",
    mode: "multi",
    sha: "a8f1…3d20",
  },
  {
    id: "snap-0820-notus",
    app: "Notus 笔记",
    deploy: "dep-notus-8839a",
    time: "2026-08-20 02:00:21",
    raw: "418 MB",
    zip: "187 MB",
    files: "1,413",
    sqlite: "2",
    integrity: "WARNING",
    keep: "待重新校验",
    mode: "single",
    sha: "c031…91aa",
  },
];

export const alerts = [
  {
    id: "al-1",
    level: "warn",
    title: "Notus 为单实例应用",
    copy: "该目录可能包含共享数据。创建计划前需要确认风险范围。",
    time: "刚刚",
    action: "确认风险",
  },
  {
    id: "al-2",
    level: "bad",
    title: "Mastodon 检测到 PostgreSQL",
    copy: "V1 不支持服务型数据库，已阻止创建 ZIP。",
    time: "6 分钟前",
    action: "查看应用",
  },
  {
    id: "al-3",
    level: "good",
    title: "网盘空间充足",
    copy: "当前使用 38.4 GB / 100 GB，保留策略运行正常。",
    time: "今天 08:10",
    action: "查看存储",
  },
];

export const navGroups = [
  {
    label: "工作台",
    items: [
      ["overview", "概览", "grid"],
      ["applications", "应用", "apps"],
      ["plans", "备份计划", "calendar"],
      ["tasks", "任务中心", "tasks"],
    ],
  },
  {
    label: "资产",
    items: [
      ["backups", "备份库", "archive"],
      ["storage", "存储", "harddrive"],
      ["alerts", "告警", "bell"],
    ],
  },
  { label: "偏好", items: [["settings", "设置", "settings"]] },
];
