/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OIDC Authorization Code with PKCE */
        get: {
            parameters: {
                query?: {
                    return_to?: components["parameters"]["ReturnTo"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Lazycat OIDC */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["IdentityMismatch"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete OIDC login and create a server-side session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the originally requested application path */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["SessionRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current verified session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                401: components["responses"]["SessionRequired"];
                403: components["responses"]["IdentityMismatch"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    q?: string;
                    mode?: "single" | "multi";
                    capability_status?: components["schemas"]["CapabilityStatus"];
                    protection_status?: "PROTECTED" | "UNPROTECTED";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Persisted current-tenant application instances */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationList"];
                    };
                };
                400: components["responses"]["ApiError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a coalesced current-tenant catalog sync */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncAccepted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{appid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    appid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logical application with its current-tenant instances */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationDetail"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{deployId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deployId: components["parameters"]["DeployId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant application instance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationInstance"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{deployId}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a coalesced catalog refresh containing this instance's probe */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deployId: components["parameters"]["DeployId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Probe refresh accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncAccepted"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{deployId}/backup-scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read safe relative paths for a current-tenant selective backup plan */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    q?: string;
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path: {
                    deployId: components["parameters"]["DeployId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Relative metadata only */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupScopeCatalog"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{deployId}/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue one bounded manual backup for a current-tenant instance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deployId: components["parameters"]["DeployId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ManualBackupRequest"];
                };
            };
            responses: {
                /** @description Manual backup accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManualBackupAccepted"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
                409: components["responses"]["ApiError"];
                429: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one current-tenant manual backup job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Manual backup job status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupJob"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent completed current-tenant snapshots */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot records with safe relative storage metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups/{snapshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one current-tenant snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    snapshotId: components["parameters"]["SnapshotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups/{snapshotId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Perform a fast current-tenant ZIP and manifest verification */
        post: {
            parameters: {
                query?: {
                    mode?: "quick" | "full";
                };
                header?: never;
                path: {
                    snapshotId: components["parameters"]["SnapshotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Verification completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
                409: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant backup plans */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanList"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanInput"];
                };
            };
            responses: {
                /** @description Plan created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupPlan"];
                    };
                };
                400: components["responses"]["ApiError"];
                409: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: components["parameters"]["PlanId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupPlan"];
                    };
                };
                404: components["responses"]["ResourceNotFound"];
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: components["parameters"]["PlanId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanInput"];
                };
            };
            responses: {
                /** @description Plan updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupPlan"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: components["parameters"]["PlanId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanRunAccepted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: components["parameters"]["PlanId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan paused */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupPlan"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: components["parameters"]["PlanId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan resumed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupPlan"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant batches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    batchId: components["parameters"]["BatchId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant batch */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupBatch"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: string;
                    batch_id?: string;
                    deploy_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task and attempts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellation accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupTask"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retry queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupTask"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups/{snapshotId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    snapshotId: components["parameters"]["SnapshotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ZIP file index */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotFileList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups/{snapshotId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    snapshotId: components["parameters"]["SnapshotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Export completed */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExportAccepted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant storage summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StorageSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Library scan completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StorageSummary"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current tenant operational overview */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Overview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current-tenant in-app alerts */
        get: {
            parameters: {
                query?: {
                    status?: "OPEN" | "MUTED" | "RESOLVED" | "ALL";
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant alerts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    alertId: components["parameters"]["AlertId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alert marked read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    alertId: components["parameters"]["AlertId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alert resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertId}/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    alertId: components["parameters"]["AlertId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MuteAlertRequest"];
                };
            };
            responses: {
                /** @description Alert temporarily muted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read current-tenant safe defaults */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        /** Update current-tenant safe defaults */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            responses: {
                /** @description Saved settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["ApiError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current-tenant audit activity */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant audit entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receive bounded current-tenant Server-Sent Events */
        get: {
            parameters: {
                query?: {
                    after?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current-tenant event stream. A new stream without a cursor starts at the current event head and emits `stream.ready`; reconnecting clients pass `after` to receive missed events. REST remains authoritative after reconnect. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Session: {
            uid: string;
            subject: string;
            displayName: string;
            email?: string;
            /** @enum {string} */
            role: "NORMAL" | "ADMIN";
            tenantUid: string;
            /** Format: date-time */
            expiresAt: string;
            identityVerified: boolean;
        };
        /** @enum {string} */
        CapabilityStatus: "BACKUPABLE" | "BACKUPABLE_SHARED_WARNING" | "NO_DATA" | "UNSUPPORTED_DATABASE" | "SYSTEM_UNSUPPORTED" | "SOURCE_MAPPING_AMBIGUOUS" | "SOURCE_NOT_READY" | "SOURCE_PERMISSION_DENIED" | "SOURCE_INSTANCE_NOT_FOUND" | "SOURCE_OWNER_MISMATCH" | "RUNTIME_APPVAR_PROJECTION_NOT_VISIBLE" | "PROBE_FAILED";
        DatabaseFinding: {
            type: string;
            /** @description Source-relative path only */
            path: string;
            supported: boolean;
            reason?: string;
        };
        ApplicationInstance: {
            appid: string;
            name: string;
            version?: string;
            /**
             * Format: uri
             * @description Lazycat catalog application icon URL
             */
            icon?: string;
            deployId: string;
            multiInstance: boolean;
            capabilityStatus: components["schemas"]["CapabilityStatus"];
            /** @enum {string} */
            protectionStatus: "PROTECTED" | "UNPROTECTED";
            /** @enum {string} */
            readOnlyMode?: "service-enforced";
            /** Format: int64 */
            totalBytes: number;
            fileCount: number;
            sqliteCount: number;
            skippedCount: number;
            databaseFindings?: components["schemas"]["DatabaseFinding"][];
            /** Format: date-time */
            lastProbedAt?: string;
            /** Format: date-time */
            lastSyncedAt: string;
            /** Format: date-time */
            lastBackupAt?: string;
            probeErrorCode?: string;
        };
        SyncStatus: {
            /** @enum {string} */
            state: "IDLE" | "RUNNING" | "SUCCEEDED" | "FAILED";
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            errorCode?: string;
        };
        ApplicationList: {
            items: components["schemas"]["ApplicationInstance"][];
            nextCursor?: string;
            sync: components["schemas"]["SyncStatus"];
        };
        ApplicationDetail: {
            appid: string;
            name: string;
            version?: string;
            instances: components["schemas"]["ApplicationInstance"][];
        };
        SyncAccepted: {
            accepted: boolean;
            started: boolean;
            sync: components["schemas"]["SyncStatus"];
        };
        ManualBackupRequest: {
            /** @description Deprecated compatibility metadata. Shared-instance risk is displayed but does not gate backup creation. */
            sharedRiskAccepted?: boolean;
        };
        BackupJob: {
            id: string;
            appid: string;
            applicationName: string;
            /**
             * Format: uri
             * @description Lazycat catalog application icon URL
             */
            icon?: string;
            applicationVersion?: string;
            deployId: string;
            multiInstance: boolean;
            sharedRiskAccepted: boolean;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            errorCode?: string;
            snapshotId?: string;
            planId?: string;
            batchId?: string;
            taskId?: string;
            triggerType?: string;
            /** Format: date-time */
            scheduledAt?: string;
            scope?: components["schemas"]["BackupScope"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        ManualBackupAccepted: {
            /** @constant */
            accepted: true;
            job: components["schemas"]["BackupJob"];
        };
        Snapshot: {
            id: string;
            jobId: string;
            appid: string;
            applicationName: string;
            /**
             * Format: uri
             * @description Lazycat catalog application icon URL
             */
            icon?: string;
            applicationVersion?: string;
            deployId: string;
            multiInstance: boolean;
            sharedInstanceWarning: boolean;
            /** @enum {string} */
            status: "COMPLETED";
            /** @description Safe path relative to MimiAppBakcup; never an absolute source or host path. */
            storagePath: string;
            /**
             * @description Whether the recorded cloud directory is currently reachable; detail views do not run archive verification.
             * @enum {string}
             */
            storageStatus?: "AVAILABLE" | "MISSING" | "INACCESSIBLE";
            scope?: components["schemas"]["BackupScope"];
            /** @enum {string} */
            archiveName: "snapshot.zip";
            /** Format: int64 */
            archiveSize: number;
            archiveSha256: string;
            /** Format: int64 */
            originalBytes: number;
            fileCount: number;
            directoryCount: number;
            sqliteCount: number;
            skippedCount: number;
            warningCount: number;
            /** Format: date-time */
            capturedAt: string;
            /** Format: date-time */
            finishedAt: string;
            /** @enum {string} */
            verificationStatus: "VERIFIED" | "FAILED";
            /** Format: date-time */
            verifiedAt?: string;
            planId?: string;
            batchId?: string;
            taskId?: string;
            triggerType?: string;
            /** @enum {string} */
            retentionStatus?: "ACTIVE" | "TRASHED";
            /** Format: date-time */
            trashedAt?: string;
        };
        SnapshotList: {
            items: components["schemas"]["Snapshot"][];
            nextCursor?: string;
        };
        PlanTarget: {
            deployId: string;
            /** @description Application identifier resolved from the current application catalog. */
            appid?: string;
            /** @description Display metadata resolved from the current application catalog. */
            applicationName?: string;
            /**
             * Format: uri
             * @description Lazycat catalog application icon URL
             */
            icon?: string;
            /**
             * @deprecated
             * @description Compatibility metadata; it does not gate plan creation.
             */
            sharedRiskAccepted?: boolean;
            scope?: components["schemas"]["BackupScope"];
        };
        BackupScope: {
            /** @enum {string} */
            mode: "FULL" | "CORE" | "CUSTOM";
            directories?: string[];
            files?: string[];
            revision: number;
            /** @description Server-generated readable range summary. */
            summary?: string;
        };
        PlanPauseReason: {
            code: string;
            deployId: string;
            path?: string;
            expected?: string;
            /** Format: date-time */
            detectedAt: string;
            scopeRevision?: number;
        };
        ScopeEntry: {
            path: string;
            /** @enum {string} */
            type: "directory" | "file";
            /** Format: int64 */
            size: number;
            sqlite: boolean;
            selectable: boolean;
        };
        BackupScopeCatalog: {
            items: components["schemas"]["ScopeEntry"][];
            nextCursor?: string;
        };
        RetryPolicy: {
            maxRetries: number;
            backoffSeconds: number;
        };
        RetentionPolicy: {
            keepLast: number;
            keepDaily: number;
            keepWeekly: number;
            keepMonthly: number;
            trashGraceHours: number;
        };
        PlanInput: {
            name: string;
            /** @enum {string} */
            targetKind: "EXPLICIT";
            targets: components["schemas"]["PlanTarget"][];
            /**
             * @deprecated
             * @description Compatibility metadata; it does not gate plan creation.
             */
            sharedRiskAccepted?: boolean;
            /** @enum {string} */
            scheduleType: "MANUAL" | "HOURLY" | "DAILY" | "WEEKLY" | "CRON";
            /**
             * @description Local execution time for daily and weekly schedules.
             * @default 02:00
             */
            executionTime: string;
            cronExpression?: string;
            timezone: string;
            enabled: boolean;
            catchUp: boolean;
            maxCatchUpSeconds: number;
            retry: components["schemas"]["RetryPolicy"];
            retention: components["schemas"]["RetentionPolicy"];
        };
        BackupPlan: components["schemas"]["PlanInput"] & {
            id: string;
            /** Format: date-time */
            nextRunAt?: string;
            pauseReason?: components["schemas"]["PlanPauseReason"];
            /** Format: date-time */
            lastScheduledAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PlanList: {
            items: components["schemas"]["BackupPlan"][];
        };
        BackupBatch: {
            id: string;
            planId?: string;
            planName?: string;
            /** @enum {string} */
            triggerType: "manual" | "scheduled";
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "SKIPPED";
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            totalTasks: number;
            succeeded: number;
            failed: number;
            skipped: number;
            running: number;
            queued: number;
        };
        BatchList: {
            items: components["schemas"]["BackupBatch"][];
            nextCursor?: string;
        };
        BackupTask: {
            id: string;
            batchId: string;
            planId?: string;
            backupJobId: string;
            appid: string;
            applicationName: string;
            /**
             * Format: uri
             * @description Lazycat catalog application icon URL
             */
            icon?: string;
            deployId: string;
            multiInstance: boolean;
            sharedRiskAccepted: boolean;
            triggerType: string;
            /** @enum {string} */
            status: "QUEUED" | "LEASED" | "PRECHECKING" | "SCANNING" | "SQLITE_SNAPSHOT" | "ZIP_WRITING" | "VERIFYING" | "COMMITTING" | "SUCCEEDED" | "SUCCEEDED_WITH_WARNINGS" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "SKIPPED" | "INTERRUPTED";
            priority: number;
            attemptCount: number;
            maxRetries: number;
            retryBackoffSeconds: number;
            errorCode?: string;
            /** Format: date-time */
            availableAt: string;
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: date-time */
            leaseExpiresAt?: string;
            /** Format: date-time */
            heartbeatAt?: string;
            snapshotId?: string;
            scope?: components["schemas"]["BackupScope"];
            scopeValidation?: components["schemas"]["PlanPauseReason"];
        };
        TaskAttempt: {
            id: string;
            taskId: string;
            attempt: number;
            status: string;
            errorCode?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        TaskList: {
            items: components["schemas"]["BackupTask"][];
            nextCursor?: string;
        };
        TaskDetail: {
            task: components["schemas"]["BackupTask"];
            attempts: components["schemas"]["TaskAttempt"][];
        };
        PlanRunAccepted: {
            /** @constant */
            accepted: true;
            batch: components["schemas"]["BackupBatch"];
        };
        SnapshotFile: {
            /** @description ZIP-internal relative path only */
            path: string;
            /** @enum {string} */
            type: "file" | "sqlite";
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            modified: string;
        };
        SnapshotFileList: {
            items: components["schemas"]["SnapshotFile"][];
        };
        ExportAccepted: {
            /** @constant */
            accepted: true;
            /** @description Safe path relative to MimiAppBakcup. */
            exportPath: string;
        };
        StorageSummary: {
            snapshotCount: number;
            /** Format: int64 */
            archiveBytes: number;
            /** Format: int64 */
            availableBytes: number;
            partialCount: number;
            missingCount: number;
            /** Format: date-time */
            lastVerifiedAt?: string;
        };
        Settings: {
            /** @enum {string} */
            locale: "zh-CN" | "en-US";
            timezone: string;
            catchUp: boolean;
            maxCatchUpSeconds: number;
            retry: components["schemas"]["RetryPolicy"];
            retention: components["schemas"]["RetentionPolicy"];
            notifyFirstFailure: boolean;
            notifySuccess: boolean;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        Alert: {
            id: string;
            /** @enum {string} */
            level: "INFO" | "WARNING" | "CRITICAL" | "EMERGENCY";
            type: string;
            code: string;
            title: string;
            message: string;
            referenceType?: string;
            referenceId?: string;
            /** @enum {string} */
            status: "OPEN" | "MUTED" | "RESOLVED";
            /** Format: date-time */
            readAt?: string;
            /** Format: date-time */
            resolvedAt?: string;
            /** Format: date-time */
            mutedUntil?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AlertList: {
            items: components["schemas"]["Alert"][];
            nextCursor?: string;
        };
        MuteAlertRequest: {
            /** @default 60 */
            minutes: number;
        };
        AuditEntry: {
            id: string;
            action: string;
            subject?: string;
            entityType?: string;
            entityId?: string;
            /** @description Safe operational metadata; no secret */
            metadata?: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditList: {
            items: components["schemas"]["AuditEntry"][];
            nextCursor?: string;
        };
        Overview: {
            applicationCount: number;
            backupableCount: number;
            protectedCount: number;
            unprotectedCount: number;
            unsupportedCount: number;
            noDataCount: number;
            queuedTasks: number;
            runningTasks: number;
            succeeded24h: number;
            failed24h: number;
            /** @description Total task records for the current tenant */
            taskCount: number;
            unreadAlerts: number;
            /** @description Total alert records for the current tenant */
            alertCount: number;
            storage: components["schemas"]["StorageSummary"];
            nextPlans: components["schemas"]["BackupPlan"][];
            recentActivity: components["schemas"]["AuditEntry"][];
        };
        ApiError: {
            code: string;
            message: string;
            requestId: string;
            params?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Safe, localizable application error */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        SessionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        IdentityMismatch: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ResourceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        ReturnTo: string;
        Cursor: string;
        Limit: number;
        DeployId: string;
        JobId: string;
        SnapshotId: string;
        PlanId: string;
        BatchId: string;
        TaskId: string;
        AlertId: string;
        TaskLimit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
